# Generated by Django 4.1.7 on 2023-09-10 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "title",
                    models.CharField(default="", max_length=45, verbose_name="课程标题"),
                ),
                (
                    "teacher",
                    models.CharField(default="", max_length=30, verbose_name="教师"),
                ),
                (
                    "assistant",
                    models.CharField(default="", max_length=30, verbose_name="助教"),
                ),
                (
                    "location",
                    models.CharField(default="", max_length=25, verbose_name="上课地点"),
                ),
                ("stock", models.IntegerField(default=80, verbose_name="剩余数量")),
                (
                    "opening_time",
                    models.SmallIntegerField(
                        choices=[
                            (1, "星期一"),
                            (2, "星期二"),
                            (3, "星期三"),
                            (4, "星期四"),
                            (5, "星期五"),
                            (6, "星期六"),
                            (7, "星期天"),
                        ],
                        default=1,
                        verbose_name="上课时间",
                    ),
                ),
                (
                    "specific_time",
                    models.CharField(
                        default="18:45-21:45", max_length=30, verbose_name="具体时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "课程信息表",
                "verbose_name_plural": "课程信息表",
                "db_table": "course_info_table",
            },
        ),
        migrations.CreateModel(
            name="CourseTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("start_time", models.DateField(verbose_name="开始时间")),
                ("end_time", models.DateField(verbose_name="结束时间")),
                ("start_choice_time", models.DateField(verbose_name="选课开始时间")),
                ("end_choice_time", models.DateField(verbose_name="选课结束时间")),
                ("index", models.IntegerField(default=1, verbose_name="期")),
            ],
            options={
                "verbose_name": "第几期",
                "verbose_name_plural": "第几期",
                "db_table": "course_time_table",
            },
        ),
        migrations.CreateModel(
            name="CourseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "name",
                    models.CharField(default="", max_length=30, verbose_name="类型名"),
                ),
                (
                    "logo",
                    models.CharField(default="", max_length=20, verbose_name="类型标记"),
                ),
            ],
            options={
                "verbose_name": "课程类型表",
                "verbose_name_plural": "课程类型表",
                "db_table": "course_type_table",
            },
        ),
        migrations.CreateModel(
            name="SelectedCourseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                (
                    "course_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.courseinfo",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "已选课程信息表",
                "verbose_name_plural": "已选课程信息表",
                "db_table": "selected_course_info_table",
            },
        ),
        migrations.CreateModel(
            name="CoursePeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_delete", models.BooleanField(default=False, verbose_name="删除标记")),
                ("start_time", models.DateField(verbose_name="开始时间")),
                ("end_time", models.DateField(verbose_name="结束时间")),
                ("index", models.IntegerField(default=1, verbose_name="阶段")),
                (
                    "course_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.coursetime",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程阶段表",
                "verbose_name_plural": "课程阶段表",
                "db_table": "course_period_table",
            },
        ),
        migrations.AddField(
            model_name="courseinfo",
            name="course_period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.courseperiod"
            ),
        ),
        migrations.AddField(
            model_name="courseinfo",
            name="course_time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.coursetime"
            ),
        ),
        migrations.AddField(
            model_name="courseinfo",
            name="course_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.coursetype"
            ),
        ),
    ]
