# Generated by Django 4.1.7 on 2023-09-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetype",
            name="logo",
            field=models.CharField(default="", max_length=35, verbose_name="类型标记"),
        ),
        migrations.AlterField(
            model_name="coursetype",
            name="name",
            field=models.CharField(default="", max_length=40, verbose_name="类型名"),
        ),
    ]
