# Generated by Django 4.1.7 on 2023-09-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_coursetime_end_choice_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseinfo",
            name="nature",
            field=models.BooleanField(default=True, verbose_name="课程性质"),
        ),
    ]
