# Generated by Django 4.1.7 on 2023-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_myuser_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="gender",
            field=models.BooleanField(default=True, verbose_name="性别"),
        ),
    ]
