# Generated by Django 4.1.7 on 2023-10-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework", "0002_alter_homework_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="size",
            field=models.IntegerField(default=0, verbose_name="文件大小"),
        ),
    ]
